--- #YAML:1.0
name:               CPAN-Reporter-Smoker-Safer
version:            0.01
abstract:           Turnkey smoking of installed distros
author:
    - David Westbrook <dwestbrook@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN:                 0
    CPAN::Reporter:       0
    CPAN::Reporter::Smoker:  0
    perl:                 5.006001
    POSIX:                0
    Test::Differences:    0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
